### ISSUE TITLE
Activating the skill on alexa web page

### ISSUE THREAD

**Issue by rmcbc** [ckhmer1/node-red-contrib-alexa-virtual-smarthome#1]
I got this error after trying to enable the skill:

We were unable to link Smart Home at this time.

**Comment by rmcbc** [comment]
Just to clarify:

5 - Your Client ID
6 - Your Secret

You can define any values for this fields? And them match them in nodered?

**Comment by rmcbc** [comment]
All the first tests are ok.

When testing the lambda function:

{
  "errorMessage": "HTTPSConnectionPool(host='avsh.ruicaridade.eu', port=443): Read timed out. (read timeout=10.0)",
  "errorType": "ReadTimeoutError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 59, in lambda_handler\n    response = http.request(\n",
    "  File \"/var/runtime/urllib3/request.py\", line 78, in request\n    return self.request_encode_body(\n",
    "  File \"/var/runtime/urllib3/request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n",
    "  File \"/var/runtime/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n",
    "  File \"/var/runtime/urllib3/connectionpool.py\", line 755, in urlopen\n    retries = retries.increment(\n",
    "  File \"/var/runtime/urllib3/util/retry.py\", line 531, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n",
    "  File \"/var/runtime/urllib3/packages/six.py\", line 735, in reraise\n    raise value\n",
    "  File \"/var/runtime/urllib3/connectionpool.py\", line 699, in urlopen\n    httplib_response = self._make_request(\n",
    "  File \"/var/runtime/urllib3/connectionpool.py\", line 447, in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n",
    "  File \"/var/runtime/urllib3/connectionpool.py\", line 336, in _raise_timeout\n    raise ReadTimeoutError(\n"
  ]
}

**Comment by ckhmer1** [comment]
Hi,
it seems that the host is not reachable from Alexa lambda.

Is it reachable?

**Comment by rmcbc** [comment]
@ckhmer1 it was not reachable but now it is.
Now all is working, except the new devices created on Node Red are not visible by Alexa App.
I don't see any error in the logs, do you have any ideas to help me debug this problem?

**Comment by ckhmer1** [comment]
How did You configure the devices?
Try starting with light with ON/ON (Power Controller).
