### ISSUE TITLE
Contact Sensor

### ISSUE THREAD

**Issue by sikousikou** [ckhmer1/node-red-contrib-alexa-virtual-smarthome#2]
hello many thanks for the great job works very well
except for the contact sensor. we generated and appears in the alexa app but does not work alex app shows the message "a problem has occurred"
sorry for my bad english, i use google to translate

**Comment by ckhmer1** [comment]
I've released un updated version fixing this problem.

**Comment by ckhmer1** [comment]
Hi,
in general, You can get the state of a node sending it a topic with value 'getstate'.

Because the motion and contact sensors use the same name 'detectionState' for the state, i have to differentiate them.

Contact sensors have the state 'contactDetectionState' and motion sensors have the state 'motionDetectionState'.

**Comment by sikousikou** [comment]
how can i see the log of the request and response

**Comment by ckhmer1** [comment]
You get a lot of 429 "Too Many Requests" errors, please check Your flow for loops.

**Comment by ckhmer1** [comment]
I've no error 429 on my log, you still have loops.
Try removing so nodes related to asked except one contact sensor and try again

**Comment by ckhmer1** [comment]
In the log You posted, I see that Alexa sends a ReportState request and the node responds with a StateReport. The response seems correct to me.
I've released an updated version. could You please post again the log after the update?
Thanks

**Comment by sikousikou** [comment]
With the update, the request window now works correctly, thanks for your great work
add a Paypal donation button to your Github repo please ;)

**Comment by ckhmer1** [comment]
Hi,
Thanks for the feedback.
Did you succeed also to make doorbell and camera working?
The camera needs a steaming server.

**Comment by sikousikou** [comment]
doorbell works well

with the camera it didn't bare to run.
I have a Reolink 410w camera with an RTSP stream. I did as in the test. but when I ask alexa (Echo Show 8) show me door camera she answers "door camera does not support this"

`{
    "cameraStreams": [
        {
            "uri": "rtsp://xxxx:xxxx@192.168.1.110:554/h264Preview_01_main",
            "expirationTime": "2025-02-03T16:20:50.52Z",
            "idleTimeoutSeconds": 30,
            "protocol": "RTSP",
            "resolution": {
                "width": 1920,
                "height": 1080
            },
            "authorizationType": "BASIC",
            "videoCodec": "H264",
            "audioCodec": "AAC"
        }
    ],
    "imageUri": "http://192.168.1.110/cgi-bin/api.cgi?cmd=Snap&channel=0&user=xxxx&password=xxxxx"
}`

LOG:
`2 Nov 09:22:48 - [error] [alexa-adapter:Alexa skill] smarthome_post: execDirective error TypeError: Cannot read property 'width' of undefined`

**Comment by ckhmer1** [comment]
I've released a new version fixing this problem.
Could you please update and let me know.
Thanks

**Comment by sikousikou** [comment]
I made an update to 0.22
if I ask alexa show me door camera answers "Ok" then she says "door camera does not react"
no message is shown in the log just this
`AlexaDeviceNode:updateState set "cameraStreams" to [{"uri":"rtsp://xxxxx:xxxx@192.168.1.110:554/h264Preview_01_main","expirationTime":"2025-02-03T16:20:50.52Z","idleTimeoutSeconds":30,"protocol":"RTSP","resolution":{"width":1920,"height":1080},"authorizationType":"BASIC","videoCodec":"H264","audioCodec":"AAC"}]
AlexaDeviceNode:updateState set "imageUri" to "http://192.168.1.110/cgi-bin/api.cgi?cmd=Snap&channel=0&user=xxxx&password=xxxxxx"`

**Comment by ckhmer1** [comment]
I've released a new version fixing a camera problem.
Could you please update and let me know.
Thanks

**Comment by sikousikou** [comment]
I installed the update
if i ask alexa: show me the xxx camera she answers ok then says i have difficulty to reach ZERO

if I inject camera data into the node it stays with alexa node Unknown somehow the camera information is not injected

Even if I use the inject node from the example, the same results

![Alexa_Cam](https://user-images.githubusercontent.com/7949811/154810124-89ca7653-e0a4-4646-be89-6e8eb0b8332d.png)

**Comment by ckhmer1** [comment]
Hi,
I'm sorry for the delay ,I've just fixed this last issues.
I close this issue, please open another issue if You have further problem with camera node.
Thanks
