### ISSUE TITLE
Authication server

### ISSUE THREAD

**Issue by philm001** [ckhmer1/node-red-contrib-alexa-virtual-smarthome#3]
Hello,
Very good tutorial. Although there are some parts that need to be updated since Amazon changed a few things. 

One quick question, there is no guide or pre-req stating that you need an authentication server for the Oauth or how to setup the directories on the Node red installation.

Would you be able to tell me how to set these up?

For the authenticating, I have been using this guide:
https://coderedirect.com/questions/512574/whats-an-easy-way-to-setup-oauth-for-an-amazon-alexa-connected-home-skill

But, if I use this method, there is an issue with the Lambda function script where the BASE_URL does not point to the node red. Is there a way to make the script compatible with the above link and without having the authentication server on the node red installation (Just fyi, I am running this on the Pi)

**Comment by ckhmer1** [comment]
Hi,
all You need is written in the instructions, I've updated them, I hope they are more clear now.

Could You please follow again the instructions from the beginning and let me know?
Thanks

**Comment by philm001** [comment]
Thank you. After re-reading, how do I get this:
https://YOUR_DOMAIN.COM/alexa/oauth

I believe that I need to install an oauth server on the RPI. If so, what are the steps to do this?

**Comment by philm001** [comment]
Also, how and where do I create the folders:

/alexa/oauth

**Comment by philm001** [comment]
Is one of the pre-reqs for this to work that I need a local Oauth server?

**Comment by ckhmer1** [comment]
All you need is following the tutorial, a node red installation and a reverse proxy, no other servers.
You don't need to create the folder /Alexa/oauth, these are the URL to redirect from the Https reverse proxy to the Node-RED server

**Comment by philm001** [comment]
OK so where do I get the https://YOUR_DOMAIN.COM from? Is this the public IP?

**Comment by philm001** [comment]
I am assuming that the YOUR_DOMAIN.com is the address pointing to the reverse proxy

**Comment by ckhmer1** [comment]
exactly, the IP address or the domain with fixed IP or the domain with the dynamic DNS server.

**Comment by philm001** [comment]
Got, it I was able to get mostly everything figured out, however, there is one issue to take care of.

**Comment by ckhmer1** [comment]
Could You please tell me the issue You found I have to take care of?

**Comment by philm001** [comment]
So the thing is is that I need to get a free domain which be gotten at no-ip (just google) and will need a server with an accessible, public IP address.
