### ISSUE TITLE
Node Red Errors

### ISSUE THREAD

**Issue by philm001** [ckhmer1/node-red-contrib-alexa-virtual-smarthome#4]
Hello, I am getting the following errors when I deploy the server:

1) "Error: ENOENT: no such file or directory, open '/home/sysadmin/.node-red/server.key'"

2) "get_access_token evn: No codes"

3) "send_add_or_update_report get_access_token err "No codes""

Do you know what could be causing these issues? I did not install a local oauth server but used this guide:

https://coderedirect.com/questions/512574/whats-an-easy-way-to-setup-oauth-for-an-amazon-alexa-connected-home-skill

**Comment by ckhmer1** [comment]
Hi,
It seems that You are not linking correctly the Skill with Your account.

Please, follow the instructions, if You have problems, please read the Troubleshooting section and post the result here.

Thanks

**Comment by philm001** [comment]
Is it possible to use the tutorial I posted above or will I need to install a local OAuth server?

**Comment by ckhmer1** [comment]
You don't need a local oath server, just the Alexa virtual node-red and a reverse proxy

**Comment by philm001** [comment]
Great, thank you
