### ISSUE TITLE
Discovering Devices

### ISSUE THREAD

**Issue by philm001** [ckhmer1/node-red-contrib-alexa-virtual-smarthome#7]
Hello
As I am testing my back end and learning some new things, I deleted the device from my Alexa profile. 

To add it back in, do I need to ask Alexa to "Discover new devices?" I did that and it was unable to find the node red device

**Comment by ckhmer1** [comment]
Node-RED notifies Alexa for every node changes, it should not need to ask Alexa to discover the new devices, but you have to wait a bit.

**Comment by philm001** [comment]
I see, no problem. I was able to get the devices to appear again in Alexa. Thank you
