### ISSUE TITLE
Get device name

### ISSUE THREAD

**Issue by regissg** [ckhmer1/node-red-contrib-alexa-virtual-smarthome#84]
I am using a virtual device node as a BLIND to set the Alexa device volume as a percentage in combination with node-red-contrib-alexa-remote2 node. 

Here is the output of the Virtual Device node
percentage: 12
source: "alexa"
mode: "Position.Down"
directive: "SetRangeValue"
name: "hautparleur"
type: "BLINDS"

The problem is that the Virtual Device node is not providing the device name I am speaking to. Is there a way to get it?

**Comment by ckhmer1** [comment]
Hi,
Could you please share your node configuration?

**Comment by regissg** [comment]
Hello Claudio,
Here is my node config

![Capture d'écran 2024-01-20 113708](https://github.com/ckhmer1/node-red-contrib-alexa-virtual-smarthome/assets/19576754/9e153d92-db60-49e2-9d02-c0cebc668a37)

Is that what you were looking for?

**Comment by ckhmer1** [comment]
I'm trying to understand the problem . 
This node is not a node-red-contrib-alexa-virtual-smarthome node.

Do you think that the problem is from the node-red-contrib-alexa-virtual-smarthome node?

**Comment by regissg** [comment]
It seem that I have confused your node-red-contrib-alexa-virtual-smarthome with node-red-contrib-virtual-smart-home!

Sorry for that

**Comment by regissg** [comment]
Wrong node. Sorry for the confusion
