### ISSUE TITLE
Config error (red triangle) on new nodes

### ISSUE THREAD

**Issue by kxkayser** [ckhmer1/node-red-contrib-alexa-virtual-smarthome#85]
Hi.   I have the PRO subscription.  Lately, when I add a node, it shows up with a red triangle (see below).  I have tried updating the Amazon account but no help.  Originally, I think it was due to duplicate names but that has been eliminated.  Thanks.
![Capture](https://github.com/ckhmer1/node-red-contrib-alexa-virtual-smarthome/assets/46426583/5f10c509-922f-4f1e-b59e-919b77b0c9d8)
![Capture2](https://github.com/ckhmer1/node-red-contrib-alexa-virtual-smarthome/assets/46426583/079f3e87-efeb-4abb-8862-6cf562f51101)

**Comment by ckhmer1** [comment]
This is not the module that you are using.
This module is completely free, no pro subscription, no external server.
