### ISSUE TITLE
brightness command when lamp is off

### ISSUE THREAD

**Issue by sikousikou** [ckhmer1/node-red-contrib-alexa-virtual-smarthome#9]
Hi there,
I'm back :)
I updated to version 0.0.28
I have the problem with the light controller with brightness and powerstate
when I turn on the lamp then give the brightness command everything works ...
but when the lamp is off and i directly give the command set lamp to xx brightness, on Nodered I get the brightness value but with powerstate off but in the alexa app the power button is changed to on

**Comment by ckhmer1** [comment]
Hi,
the node state is updated with the info received from Alexa, if Alexa doesn't include "powerState" to on, the node doesn't modify it. Anyway, the node sends in the output the modified fields.
Should the node automatically change the powerState value to ON?

**Comment by ckhmer1** [comment]
Seems to be a bug of the Alexa app, of you change the brightness using the slider, the light indicator goes on, but if you change via voice command the light indicator remains off
